### ISSUE TITLE
Missing requirements.txt in the repo

### ISSUE THREAD

**Issue by a-shine** [bach05/SAM_annotation_tool#1]
Hi there,

Thanks for sharing this tool. It could be super useful for some research I have to carry out. I just thought I would let you know that there is no requirements.txt in the repo's root. Manually installing the dependencies was relatively straightforward, but it may be good to have for other users.

I had to install

- torch
- numpy
- segment_anything
- opencv-python (cv2)
- matplotlib

Best,
Alex

**Comment by junhua-zhang** [comment]
Hi Alex,

Thank you for sharing the dependencies. Could you please also share the versions?

Best Regards.
JH

**Comment by a-shine** [comment]
Here you go:
```
matplotlib==3.8.4
numpy==1.26.4
opencv-python==4.9.0.80
segment-anything==1.0
torch==2.2.2
torchvision==0.17.2
```

**Comment by bach05** [comment]
Thank you for alerting me, I pushed the requirements.txt file. 

If there are any problems, please let me know!

**Comment by a-shine** [comment]
Many thanks. Appreciated :)
